CREATE DATABASE Ola;
USE Ola;
SELECT COUNT(*) FROM bookings_data;
#Retrieve all successful bookings:
CREATE VIEW Successful_Booking AS
SELECT * FROM Ola.bookings_data
WHERE Booking_Status="Success";

#1 Calculate the percentage of successful bookings: 
SELECT
ROUND(((SELECT COUNT(*) FROM Successful_Booking) / (SELECT COUNT(*) FROM Ola.Bookings_data)*100),2) AS Success_percentage;

#2 What is the main reason for incomplete rides?
SELECT COUNT(*), Incomplete_Rides_Reason 
FROM bookings_data
WHERE Incomplete_Rides = 'Yes'
GROUP BY Incomplete_Rides_Reason 
ORDER BY COUNT(*) DESC;

#3 Which customer has the highest number of cancellations?
SELECT Customer_ID, COUNT(*) AS Cancellation_Count
FROM bookings_data
WHERE Booking_Status IN ('Canceled by Customer', 'Canceled by Driver')
GROUP BY Customer_ID
ORDER BY Cancellation_Count DESC
LIMIT 1;

#4 What Is the Average Revenue Generated by Each Vehicle Type? 
SELECT Vehicle_Type,
       ROUND(AVG(Booking_Value), 2) AS Avg_Revenue_Per_Ride
FROM Successful_Booking
GROUP BY Vehicle_Type
ORDER BY Avg_Revenue_Per_Ride DESC;
